# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43c389bf6f2e060cb616b2d1ff41bf60b1df9f8add53581fc727e6cac15b1a834022758f7e0a4b5fe0b79ec5595cf7e0a0b3aa82552e5b0884ea9ee7b9a69a32

test:
  secret_key_base: 7b5cfc49e2d08476304589d374544582714a56733abd42e6abb6f32b3ba42ad1b2e6a73b0149a2bec312ab4d6da26611c07b1849831f7b3b888a612c46e10aa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
